### PR TITLE
Fix repo name in travis button.

### PR DESCRIPTION
**Pull request by tsalo**

### CODE REVIEW

**Comment by emdupre** [comment]
Good catch! Can you fix the coveralls badge in this PR, too ?

**Comment by tsalo** [comment]
I looked at the preview after changing the coveralls badge, but it went from having info to being unknown. I think that coveralls is set to the original name of the repository still.

**Comment by emdupre** [comment]
I just re-synced the coveralls account&mdash; it has yet to trigger a build but should once this PR is submitted ! The new badge is listed on NBClab's coveralls.io

**Comment by tsalo** [comment]
So I should change the badge?

**Comment by emdupre** [comment]
That would be great! If not, no worries, I'll just open a separate PR after merging this one.

**Pull request merged**
